# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 17fd4fb1de52ed969b8028abe5c1e2858a7d9ddf905f0e29a265021672dafadbadf03e2555b629118d8c2f3e5e07be86ced9f3415190e0f88180c2b324d76682

test:
  secret_key_base: 757c5a0f254894d31c297d5b64865d53b10d8d2cc81070368640608e92aeab588b7514e30325984eed12ea775490e0ea86eb710f18c8d50bb96e557c64a60c4e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
